security:
    access_decision_manager:
        strategy:             unanimous

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: "1", roles: ["ROLE_ADMIN"] }

    firewalls:
        admin:
            pattern: ^/
            switch_user: true
            context: user
            anonymous: true
            http_basic:
                realm: 'Secured Area'
    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
