zicht_page:
    aliasing: true

    pageClass: 'Acme\SiteBundle\Entity\Page'
    contentItemClass: ''
    types:
        page:
            article: Acme\SiteBundle\Entity\Page\ArticlePage
        contentItem:
            text:    Acme\SiteBundle\Entity\ContentItem\Text

    admin:
        base:
            page: acme.admin.page
            contentItem: acme.admin.content_item

